### ISSUE TITLE
Farming Policy attached to farm should migrate existing node policies

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/tfchain_graphql#59]
When a farming policy is attached to a farm, only new nodes receive this policy. We also want to migrate all existing nodes to this new policy.

**Comment by DylanVerstraete** [comment]
fixed in https://github.com/threefoldtech/tfchain_graphql/commit/f416e97a9c70f5a70747861c9b912c9bfbedadf5

Will be deployed on devnet later today

**Comment by mohamedamer453** [comment]
The `farmingPolicyId` for the mentioned node is still the same.

![image](https://user-images.githubusercontent.com/101194226/188647985-fde6aeb2-fa0c-4f38-963a-f181171d6fc2.png)

and i have tried the same flow with another node on qanet `node 6` and again it was updated on the chain but on grid_proxy and graphql the old id is still displayed.

```
{
  version: 5
  id: 6
  farmId: 30
  twinId: 80
  resources: {
    hru: 9,001,778,946,048
    sru: 512,110,190,592
    cru: 24
    mru: 202,801,156,096
  }
  location: {
    longitude: 4.3447
    latitude: 50.8509
  }
  country: Belgium
  city: Unknown
  publicConfig: {
    ip4: {
      ip: 250.123.145.254/24
      gw: 226.123.145.241
    }
    ip6: {
      ip: 2001:db8:3333:4444:5555:6666:7777:fff1/64
      gw: 2001:db08:3333:4444:5555:6666:7777:8888
    }
    domain: null
  }
  created: 1,662,385,368
  farmingPolicyId: 3
  interfaces: [
    {
      name: zos
      mac: 0c:c4:7a:30:7b:ac
      ips: [
        10.2.0.162
        2a02:1802:5e:12:ec4:7aff:fe30:7bac
      ]
    }
  ]
  certification: Diy
  secureBoot: false
  virtualized: false
  serialNumber: OM22S41340
  connectionPrice: 80
}
```
![image](https://user-images.githubusercontent.com/101194226/188648657-5233114c-7d69-4f39-bce7-9bb32bca0171.png)

**Comment by DylanVerstraete** [comment]
should be fixed when https://github.com/threefoldtech/tf_operations/issues/1142 is done

**Comment by DylanVerstraete** [comment]
Fixed

![image](https://user-images.githubusercontent.com/17138347/188908862-744a6a77-5c5d-43d7-a94b-f1806af3a539.png)

**Comment by mohamedamer453** [comment]
also fixed on qanet 

![image](https://user-images.githubusercontent.com/101194226/188909145-79e64b4a-263e-4d72-a691-9d32cf433934.png)
